-- =========================================================
-- Smart Hostel Finder — Sample Data (optional but recommended)
-- Language: SQL (PostgreSQL)
-- Run this AFTER schema.sql so you have hostels to see on the site.
-- Note: the password for both sample accounts below is "password123"
-- (it's stored as a bcrypt hash, generated by the signup route logic).
-- =========================================================

INSERT INTO users (full_name, email, password_hash, role)
VALUES
('Ama Owusu', 'owner@example.com', '$2a$10$CwTycUXWue0Thq9StjUM0uJ8G6r5vJHchTMkOo7RS0dK4bqUyrfF6', 'owner'),
('Kojo Mensah', 'student@example.com', '$2a$10$CwTycUXWue0Thq9StjUM0uJ8G6r5vJHchTMkOo7RS0dK4bqUyrfF6', 'student');

INSERT INTO hostels (owner_id, name, region, address, description, has_cctv, has_shuttle, nearby_bus_stop, is_verified, cover_image_url)
VALUES
(1, 'Legon Hills Hostel', 'Legon', 'Okponglo, near Legon', 'A quiet, secure hostel a 5-minute walk from the University of Ghana main gate.', TRUE, TRUE, 'Okponglo Junction', TRUE, ''),
(1, 'Pentagon Student Lodge', 'Legon', 'Pentagon Road, Legon', 'Popular hostel with a lively community and reliable water/electricity supply.', TRUE, FALSE, 'Pentagon Bus Stop', TRUE, ''),
(1, 'KNUST Green Court', 'Kumasi', 'Ayeduase, near KNUST', 'Modern rooms close to KNUST with 24-hour security.', TRUE, TRUE, 'Ayeduase Junction', FALSE, '');

INSERT INTO rooms (hostel_id, room_type, price_per_year, total_units, available_units)
VALUES
(1, '1 in a room', 4500.00, 10, 3),
(1, '2 in a room', 3200.00, 20, 8),
(2, '4 in a room', 2100.00, 30, 12),
(2, '2 in a room', 2900.00, 15, 0),
(3, '2 in a room', 3000.00, 25, 10);
